@startuml
hide footbox

!ifndef DIAGRAM
!define DIAGRAM

interface Particle {
    +render(): void
}

class SimpleParticle implements Particle {
    +render(): void
}

class ParticleGroup implements Particle {
    -particles: List<Particle>
    +addParticle(particle: Particle): void
    +removeParticle(particle: Particle): void
    +render(): void
}

Particle <|-- SimpleParticle
Particle <|-- ParticleGroup

!endif

@enduml
