@startuml
hide footbox

class GameLevel {
    -enemies: List<String>
    -items: List<String>
    -decorations: List<String>
    +GameLevel()
    +addEnemy(enemy: String): void
    +addItem(item: String): void
    +addDecoration(decoration: String): void
    +display(): void
}

interface LevelBuilder {
    +reset(): void
    +addEnemies(enemies: List<String>)
    +addItems(items: List<String>)
    +addDecorations(decorations: List<String>)
    +build(): GameLevel
}

class ConcreteLevelBuilder {
    -level: GameLevel
    +ConcreteLevelBuilder()
    +reset(): void
    +addEnemies(enemies: List<String>)
    +addItems(items: List<String>)
    +addDecorations(decorations: List<String>)
    +build(): GameLevel
}

class LevelDirector {
    -builder: LevelBuilder
    +LevelDirector(builder: LevelBuilder)
    +make(type: LevelType): GameLevel
}

enum LevelType {
    Cave
    Dungeon
    Forest
    Castle
}

LevelDirector --> LevelType


GameLevel *-- LevelBuilder
LevelBuilder <|.. ConcreteLevelBuilder
LevelDirector --> LevelBuilder

@enduml
