@startuml SpellFactoryMethod

title Spell Factory Method

abstract class SpellFactory {
    {abstract} +createSpell(name: string, damage: int): ISpell
}

interface ISpell {
    +name
    +damage
    +cast()
    +render()   
}

class MageSpell {
    +name
    +damage
    +cast()
    +render()  
}

class HunterSpell {
    +name
    +damage
    +cast()
    +render()  
}

class FighterSpell {
    +name
    +damage
    +cast()
    +render()  
}

class HunterSpellFactory {
    +createSpell(name: string, damage: int): ISpell
}

class MageSpellFactory  {
    +createSpell(name: string, damage: int): ISpell
}

class FighterSpellFactory  {
    +createSpell(name: string, damage: int): ISpell
}

SpellFactory .left.> ISpell : creates

SpellFactory <|-right- HunterSpellFactory
SpellFactory <|-up- MageSpellFactory
SpellFactory <|-down- FighterSpellFactory

ISpell <|.up. MageSpell
ISpell <|.up. HunterSpell
ISpell <|.up. FighterSpell

@enduml