@startuml

interface Renderer {
    + render(name: String)
}

class Renderer2D implements Renderer {
    + render(name: String)
}

class Renderer3D implements Renderer {
    + render(name: String)
}

abstract class GameObject {
    - renderer: Renderer
    + GameObject(renderer: Renderer)
    + render()
}


class Enemy extends GameObject {
    + Enemy(renderer: Renderer)
    + render()
}

class Collectible extends GameObject {
    + Collectible(renderer: Renderer)
    + render()
}

GameObject --> Renderer

@enduml
