@startuml

!ifndef DIAGRAM
!define DIAGRAM

class Game {
    - state: String
    + setState(state: String)
    + save(): GameMemento
    + restore(m: GameMemento)
}

class GameMemento {
    - state: String
    + GameMemento(state: String)
    + getState(): String
}

class Player {
    - state: String
    + setState(state: String)
    + save(): PlayerMemento
    + restore(m: PlayerMemento)
}

Player +-- PlayerMemento : inner class
Game +-- GameMemento : inner class 

class PlayerMemento {
    - state: String
    + PlayerMemento(state: String)
    + getState(): String
}

class Caretaker {
    - game: Game
    - player: Player
    - gameHistory: List<GameMemento>
    - playerHistory: List<PlayerMemento>
    + saveGameState()
    + savePlayerState()
    + undoGameState()
    + undoPlayerState()
}

Game --> GameMemento
Player --> PlayerMemento
Caretaker --> Game
Caretaker --> Player
Caretaker o--> GameMemento
Caretaker o--> PlayerMemento

!endif

@enduml
