@startuml
hide footbox

interface ISword {

}

interface IShield {

}

class ElfSword implements ISword {

}

class OrcSword implements ISword {

}

class ElfShield implements IShield {

}

class OrcShield implements IShield {

}

interface IWeaponFactory {
    +createSword(): ISword
    +createShield(): IShield
}

class ElfWeaponFactory implements IWeaponFactory {
    +createSword(): ISword
    +createShield(): IShield
}

class OrcWeaponFactory implements IWeaponFactory {
    +createSword(): ISword
    +createShield(): IShield
}

@enduml
