@startuml
hide footbox

class Sword {
    +damage: int
    +Sword()
    +getDamage(): int
    +attack(): void
}

interface Weapon {
    +attack(): void
}

class BasicSword {
    +attack(): void
}

abstract class SwordDecorator implements Weapon {
    protected -decoratedSword: Weapon
    +SwordDecorator(weapon: Weapon)
    +attack(): void
}

class FireSwordDecorator extends SwordDecorator {
    +FireSwordDecorator(weapon: Weapon)
    +attack(): void
    +addFireDamage(): void
}

class PoisonSwordDecorator extends SwordDecorator {
    +PoisonSwordDecorator(weapon: Weapon)
    +attack(): void
    +addPoisonDamage(): void
}

Weapon <|-- BasicSword
Sword *-- Weapon

@enduml
