@startuml

title Enemy Factory Method

interface IEnemy {
    +attack(): void
    +clone(): IEnemy
}

class Zombie {
    -x: int
    -y: int
    -type: EnemyType
    -enemyBehavior: EnemyBehavior
    +abstract attack(): void
    +clone(): IEnemy
}

class Vampire {
    -x: int
    -y: int
    -type: EnemyType
    -enemyBehavior: EnemyBehavior
    +abstract attack(): void
    +clone(): IEnemy
}

class Werewolf {
    -x: int
    -y: int
    -type: EnemyType
    -enemyBehavior: EnemyBehavior
    +abstract attack(): void
    +clone(): IEnemy
}

abstract class IEnemyFactory {
    +abstract createIEnemy(): IEnemy
}

class ZombieFactory {
    +createIEnemy(): IEnemy
}

class VampireFactory {
    +createIEnemy(): IEnemy
}

class WerewolfFactory {
    +createIEnemy(): IEnemy
}

IEnemy <|-- Zombie
IEnemy <|-- Vampire
IEnemy <|-- Werewolf

IEnemyFactory <|-- ZombieFactory
IEnemyFactory <|-- VampireFactory
IEnemyFactory <|-- WerewolfFactory

IEnemyFactory ..> IEnemy : creates

@enduml
