@startuml
hide footbox

class GameManager {
    +register(system: GameSystem): void
    +notify(event: Event): void
}

class GameSystem {
    +receive(event: Event): void
}

GameManager o-- GameSystem : Mediates

@enduml
