@startuml
hide footbox

class Client {
    +main(): void
}

class Context {
    -strategy: Strategy
    +setStrategy(strategy: Strategy): void
    +executeStrategy(): void
}

interface EnemyBehavior {
    +execute(): void
}

class AttackBehavior implements EnemyBehavior {
    +execute(): void
}

class FleeBehavior implements EnemyBehavior {
    +execute(): void
}

class PatrolBehavior implements EnemyBehavior {
    +execute(): void
}

class Enemy {
    -behavior: EnemyBehavior
    +setBehavior(behavior: EnemyBehavior): void
    +performAction(): void
}

Client --> Context
Client ..|> FleeBehavior
Client ..|> PatrolBehavior
Client ..|> AttackBehavior
Context *--> EnemyBehavior
Enemy *-- EnemyBehavior

@enduml
