@startuml
hide footbox

interface EnemyBehavior {
    +execute(): void
}

class AttackBehavior implements EnemyBehavior {
    +execute(): void
}

class FleeBehavior implements EnemyBehavior {
    +execute(): void
}

class PatrolBehavior implements EnemyBehavior {
    +execute(): void
}
 
Vampire o--> EnemyBehavior
Werewolf o--> EnemyBehavior
Zombie o--> EnemyBehavior


class Zombie {
    -x: int
    -y: int
    -behavior: EnemyBehavior
    +setBehavior(behavior: EnemyBehavior): void
    +performAction(): void
    +abstract attack(): void
}

class Vampire {
    -x: int
    -y: int
    -behavior: EnemyBehavior
    +setBehavior(behavior: EnemyBehavior): void
    +performAction(): void
    +abstract attack(): void
}

class Werewolf {
    -x: int
    -y: int
    -behavior: EnemyBehavior
    +setBehavior(behavior: EnemyBehavior): void
    +performAction(): void
    +abstract attack(): void
}


@enduml