@startuml
hide footbox

class Client {
    +main(): void
}

class Context {
    -strategy: ShootingStrategy
    +setStrategy(strategy: ShootingStrategy): void
    +executeStrategy(): void
}

interface ShootingStrategy {
    +shoot(): void
}

class StraightShooting implements ShootingStrategy {
    +shoot(): void
}

class FanShooting implements ShootingStrategy {
    +shoot(): void
}

class Weapon {
    -strategy: ShootingStrategy
    +setStrategy(strategy: ShootingStrategy): void
    +shoot(): void
}

Client --> Context
Client ..|> StraightShooting
Client ..|> FanShooting
Context *--> ShootingStrategy
Weapon *-- ShootingStrategy

@enduml
