@startuml
hide footbox




interface ShootingStrategy {
    +shoot(): void
}

class StraightShooting implements ShootingStrategy {
    +shoot(): void
}

class FanShooting implements ShootingStrategy {
    +shoot(): void
}

class Weapon {
    -strategy: ShootingStrategy
    +setStrategy(strategy: ShootingStrategy): void
    +shoot(): void
}

Weapon o--> ShootingStrategy



@enduml
