@startuml
hide footbox

class Flyweight {
    -type: String
    -image: String
    +Flyweight(type: String, image: String)
    +operation(uniqueState: String): void
}

class FlyweightFactory {
    -cache: Map<String, Flyweight>
    +getFlyweight(type: String): Flyweight
}

class Context {
    -uniqueState: String
    -flyweight: Flyweight
    +Context(type: String, uniqueState: String)
    +operation(): void
}

class Client {
    +main(): void
}

Client --> Context
Context --> Flyweight
FlyweightFactory --> Flyweight

@enduml
