@startuml
hide footbox

!ifndef DIAGRAM
!define DIAGRAM

class JSONConfigManager {
    -instance: JSONConfigManager
    -jsonData: String
    -JSONConfigManager()
    +getInstance(): JSONConfigManager
    +loadDataFromDisk(): void
    +saveDataToDisk(): void
    +getData(): String
    +setData(data: String): void
}

JSONConfigManager --|> Singleton

!endif

@enduml
