name: PlantUML to Image

on: 
  push:
    branches:
      - ci/plant-uml-to-png-test

jobs:
  generate-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install PlantUML
      run: sudo apt-get install plantuml -y

    - name: Install Graphviz
      run: sudo apt-get install graphviz -y

    - name: Convert PlantUML to PNG
      run: |
        find UML -name "*.puml" | while read file; do
          plantuml -tpng "$file";
        done

    - name: Commit PNG files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add UML/**/*.png
        git commit -m "Add generated PNG files"
        git push origin ci/plant-uml-to-png-test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
